apiVersion: v1
kind: Namespace
metadata:
  name: foldingathome
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    app: fahclient
  name: fahclient
  namespace: foldingathome
spec:
  # replicas: 1
  selector:
    matchLabels:
      app: fahclient
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: fahclient
    spec:
      containers:
      - args:
        - -v
        - --gpu=false
        - --power=full
        - --cpus=8
        - --fold-anon=true
        - --gui-enabled=true
        - --web-enable=true
        - --command-enable=false
        - --run-as=nobody
        command:
        - /shared/usr/bin/FAHClient
        image: ubuntu:xenial
        name: fahclient
        securityContext:
          allowPrivilegeEscalation: false
          capabilities: {}
          privileged: false
          readOnlyRootFilesystem: false
          runAsNonRoot: true
          runAsUser: 65534
        ports:
            - name: web-ui
              containerPort: 7396
            - name: daemon
              containerPort: 36330
        resources:
            limits:
              memory: "8Gi"
              cpu: "350m"          
        volumeMounts:
        - mountPath: /shared
          name: shared
        workingDir: /shared/usr/bin/
      initContainers:
      - args:
        - -c
        - apt update && apt install -y wget && wget https://download.foldingathome.org/releases/public/release/fahclient/debian-testing-64bit/$(major_version)/$(package_name)
          && dpkg -x $(package_name) /shared/ && touch /shared/usr/bin/log.txt &&
          chown -R 65534:65534 /shared
        command:
        - /bin/sh
        env:
        - name: major_version
          value: v7.4
        - name: package_name
          value: fahclient_7.4.4_amd64.deb
        image: ubuntu:xenial
        name: install-fah
        resources:
          limits:
            cpu: "1"
            memory: 256Mi
        securityContext:
          allowPrivilegeEscalation: false
          privileged: false
          readOnlyRootFilesystem: false
          runAsNonRoot: false
          runAsUser: 0
        volumeMounts:
        - mountPath: /shared
          name: shared
      restartPolicy: Always
      schedulerName: default-scheduler
      volumes:
      - emptyDir: {}
        name: shared
      nodeSelector:
        juju-application: kubernetes-worker
---
apiVersion: v1
kind: Service
metadata:
  name: fahclient
  namespace: foldingathome
spec:
  selector:
    app: fahclient
  ports:
  - name: web-ui
    protocol: TCP
    port: 3
    targetPort: web-ui
    nodePort: 31739
  - name: daemon
    protocol: TCP
    port: 36330
    targetPort: daemon
    nodePort: 31330    
  type: NodePort